= KeyStoreUtils

== Purpose

To offer a simple way to get add key store and trust stores to the JVM

== Implementation

Currently, the only implementation is extracting values from CredHub via CfEnv.

This reads in the passed in environment variables, decodes the stores, and writes them to the configured temporary paths.

To take advantage of this library, please make sure it compiled locally `mvn install` and available, or via your maven repository.
After verifying availability of the JAR, please update your pom.xml to include the following

```

<dependency>
  <groupId>sh.buildit.credhub</groupId>
  <artifactId>keystore-utils</artifactId>
  <version>0.0.4</version>
</dependency>

```


=== Configuration

To use, simply add three environment variables:

* `CREDHUB_NAME`
** (Required) Name of the CredHub service bound to the application
* `CREDHUB_KEYSTORE`
** (Optional) Name of the individual credential in `CREDHUB_NAME` that contains a Base64 encoded JKS key store. By default, it assumes `key-store`
* `CREDHUB_TRUSTSTORE`
** (Optional) Name of the individual credential in `CREDHUB_NAME` that contains a Base64 encoded JKS trust store. By default, it assumes `trust-store`

an example manifest

```
---
applications:
- name: kafka-certs-test
  buildpacks:
  - java_buildpack_offline
  memory: 1G
  instances: 1
  env:
    CREDHUB_NAME: test-credhub
    CREDHUB_KEYSTORE: keystore1
    CREDHUB_TRUSTSTORE: truststore1
    JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 11.+ } }'
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
    SPRING_PROFILES_ACTIVE: cloud
```

The library also expects additional fields in the CredHub service:

* `<CREDHUB_KEYSTORE>-password`
** The key store password
* `<CREDHUB_KEYSTORE>-type`
** The key store type
* `<CREDHUB_TRUSTSTORE>-password`
** The trust store password
* `<CREDHUB_TRUSTSTORE>-type`
** The trust store type

